<?php
$P = [
  'slug'         => 'ai-fake-citations-customs-penalty-set-aside-supreme-court.php',
  'title'        => 'SC Sets Aside Order Built on AI Citations – Advocate Manish Jha',
  'meta'         => 'Supreme Court sets aside a Rs 425 crore customs penalty because the adjudicating officer relied on AI-generated fake case law. Hallucinated material vitiates.',
  'h1'           => 'Hallucinated Case Law Vitiates the Decision: Supreme Court on AI in Adjudication',
  'crumb'        => 'AI Citations — SC',
  'kicker'       => 'Supreme Court · 2 September 2026',
  'sub'          => 'Allowing an appeal from an SLP, the Court held that a decision resting on fake, AI-generated citations is no decision in the eyes of law — and remanded a Rs 425 crore penalty for fresh adjudication.',
  'date'         => '2026-09-10',
  'date_display' => '10 September 2026',
  'category'     => 'Procedure & Practice',
  'lead'         => '<p class="lead">In <em>Vijay Ghanshyam Gadiya v. Union of India</em>, Civil Appeal arising out of SLP (C) No. 15605 of 2026, 2026 INSC 947 (decided 2 September 2026), a Bench of Justice Dipankar Datta and Justice Sheel Nagu set aside a customs penalty of Rs. 425,27,99,100 — and the Gujarat High Court judgment affirming it — upon finding that the adjudicating officer had relied on AI-generated fake citations and non-existent case law. The matter was remanded for fresh adjudication. The ruling is among the sharpest statements yet from the Supreme Court on the entry of hallucinated material into formal decision-making: a decision infected by fabricated authority is, in the Court\'s words, no decision in the eyes of the law.</p>',
  'related'      => ['delhi-high-court.php' => 'Delhi High Court', 'business-corporate-law.php' => 'Commercial &amp; Corporate', 'cyber-law.php' => 'Cyber Law', 'blog.php' => 'Legal Updates'],
  'faqs'         => [
    ['What was the case about?', 'The Additional Commissioner of Customs, Surat imposed a penalty exceeding Rs. 425 crores under Section 114 of the Customs Act, 1962 for alleged misdeclaration of natural diamonds as lab-grown diamonds. The Gujarat High Court upheld the penalty in January 2026. On appeal by special leave, the Supreme Court found the adjudication order relied on citations that did not exist — apparently generated by an AI tool — and set aside both orders.'],
    ['What exactly did the Supreme Court hold about AI-generated material?', 'That reliance on fake or hallucinated authority vitiates the decision entirely. The Court held such a decision is "no decision in the eyes of the law" and that decisions are to be set aside "even if an iota of fake or hallucinated material enters the decision-making process." The defect is structural, not curable by showing other parts of the order were sound.'],
    ['Did the assessee escape the penalty altogether?', 'No. The Supreme Court remanded the matter for fresh adjudication. The vice lay in the process, so the remedy was a clean process — the merits of the misdeclaration allegation remain open before the adjudicating authority.'],
    ['What does this mean for the use of AI in legal work?', 'Verification is the professional obligation. Authorities, tribunals and counsel who use AI tools must independently confirm every citation against the official record before relying on it; the consequence of failure is now explicit — nullity of the decision and, for practitioners, exposure to professional consequences.'],
  ],
  'sources'      => [
    ['label' => 'Judgment — Vijay Ghanshyam Gadiya v. Union of India, Supreme Court of India, 2026 INSC 947 (Indian Kanoon)', 'url' => 'https://indiankanoon.org/doc/124603270/'],
  ],
];
$BODY = <<<'HTML'
<h2>How a Rs 425 crore penalty unravelled</h2>
<p>The dispute began as an orthodox customs matter: the department alleged that natural diamonds had been misdeclared as lab-grown diamonds to evade tariff consequences, and the Additional Commissioner of Customs, Surat imposed a penalty of Rs. 425,27,99,100 under Section 114 of the Customs Act, 1962. The Gujarat High Court affirmed the penalty on 20 January 2026. What surfaced before the Supreme Court was not a better argument on classification but a defect in the adjudication itself: the officer's order rested on case law that does not exist — citations bearing the hallmarks of generative AI output, never checked against any reporter or court record.</p>

<h2>The principle: an iota is enough</h2>
<div class="note">
<p>"Such a decision is no decision in the eyes of the law... Such decisions are to be set aside even if an iota of fake or hallucinated material enters the decision-making process."</p>
</div>
<p>The formulation deserves attention for its strictness. The Court did not weigh how much of the order depended on the fabricated authorities, or whether the result could be sustained on the genuine material. Once fabricated authority is found in the reasoning, the adjudication is structurally compromised: neither the affected party nor a reviewing court can know how the fiction shaped the outcome. The only remedy consistent with fairness is to set the decision aside in its entirety and direct fresh adjudication — which is what the Court ordered, leaving the merits fully open.</p>

<h2>Why the Supreme Court intervened despite concurrent findings</h2>
<p>Article 136 jurisprudence ordinarily counsels restraint where the High Court has affirmed an authority's order. But the special leave jurisdiction exists precisely for cases where the process of justice itself has miscarried. A quasi-judicial penalty of this magnitude, resting on authorities that were never real, presented not an error within jurisdiction but a nullity — and the Court treated it as such, correcting both the original order and the affirmance that had failed to catch the defect.</p>

<h2>The lessons, by audience</h2>
<div class="tiles">
<div class="tile"><strong>For adjudicating authorities and tribunals.</strong> Every citation in an order must be verified against official sources before the order issues. The judgment converts citation hygiene from good practice into a condition of validity.</div>
<div class="tile"><strong>For counsel.</strong> Submissions prepared with AI assistance carry the same duty: fabricated authority in a filing invites not only rejection but professional consequences, and — as this case shows — can destroy an otherwise winnable position.</div>
<div class="tile"><strong>For litigants facing adverse orders.</strong> The case adds a ground to the review checklist: verify the authorities the order relies upon. An order citing non-existent judgments is challengeable root and branch, whatever the underlying merits.</div>
</div>

<h2>A wider moment for Indian adjudication</h2>
<p>Generative tools are now embedded in drafting workflows across the profession and, evidently, within adjudicating authorities. The Supreme Court's response is neither prohibition nor endorsement — it is a verification standard with a nullity sanction. The direction of travel is clear: technology may assist the writing of a decision, but the authority cited must exist, and the human signing the order answers for it. For a case that began with diamonds alleged to be something they were not, the ending is fitting: authorities that were not what they claimed to be brought the entire edifice down.</p>
HTML;
include __DIR__ . '/post-layout.php';
